version: '3.8'

services:
  database:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Cayetano123
      POSTGRES_DB: db_c8288
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        NODE_ENV: docker
    container_name: backend_api
    ports:
      - "3000:3000"
    environment:
      DB_HOST: database
      DB_USER: postgres
      DB_PASS: Cayetano123
      DB_NAME: DB_C8288
      DB_PORT: 5432
      JWT_SECRET: Heredia123
      FRONTEND_URL: http://localhost:4000
    depends_on:
      - database
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_URL: http://backend:3000
    container_name: frontend_ui
    ports:
      - "4000:80"
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
